# Change these first
owner: lucienkerl # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Synology
    url: https://synology.kerl.io
  - name: Bitwarden
    url: https://bitwarden.kerl.io
  - name: Nextcloud
    url: https://nextcloud.kerl.io
  - name: Loxone
    url: http://loxone.kerl.io

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.kerl.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
